### ISSUE TITLE
Freeze of Aggregates causes invalid Cast Instructions

### ISSUE THREAD

**Issue by tgymnich** [JuliaGPU/llvm-metal#4]
https://github.com/JuliaGPU/llvm-downgrade/blob/355123f9415581fa1f5fabb0f7e7227bfbc9f43d/llvm/lib/Bitcode/Writer50/BitcodeWriter50.cpp#L2836

Emulating `freeze` instructions with `bitcasts` leads to illegal bitcode when dealing with aggregates (see [llvm language ref](https://llvm.org/docs/LangRef.html#bitcast-to-instruction)):
> The ‘bitcast’ instruction takes a value to cast, which **must be a non-aggregate** first class value, and a type to cast it to, which must also be a **non-aggregate [first class](https://llvm.org/docs/LangRef.html#t-firstclass) type.**

**Comment by maleadt** [comment]
Thanks for figuring this out. I'll add a rewrite pass to the LLVM bitcode writer.

A quicker fix may be to add this to GPUCompiler (like we already remove `freeze` for SPIR-V), but I anticipate that we may have to do more complex rewrites at some point, so having the infrastructure for it in C++ may become useful then.
